### PR TITLE
'no such file' error on first save at LOCAL_FILE_PATH

### LINKED ISSUE #38: 'no such file' error on first save at LOCAL_FILE_PATH
When running the application for the first time the user will experience an error like

```shell
Error: ENOENT: no such file or directory, open '/home/username/.local/share/cube/times.csv'
    at [stacktrace]
```

It appears to be a timing issue when creating the folder with [mkdirp](https://www.npmjs.com/package/mkdirp). The default function is asynchronous, there is a dedicated synchronized version.

`mkdirp` does not return it's internal promise, because of this it would be probably better to either switch to `mkdirp.sync ` or to create a own version.

### PR DESCRIPTION
**Pull request by Jan-Ka**
This request resolves #38, possible even #33.

This change requires the package.json to be updated to the latest versions just to be save.

### CODE REVIEW

File: constants.js [hunk 1]
```diff
@@ -1,3 +1,10 @@
...
-exports.PUSHED_FILE_PATH = xdg.data + '/cube/pushed.csv';
+var path = require('path');
+
+var localSaveDir = path.join(xdg.data, '/cube');
+var localFilePath = path.join(localSaveDir, 'times.csv');
+var pushedFilePath = path.join(localSaveDir, 'pushed.csv');
+
+exports.LOCAL_SAVE_DIR = localSaveDir;
+exports.LOCAL_FILE_PATH = localFilePath;
+exports.PUSHED_FILE_PATH = pushedFilePath;
```
Comment (icyflame) [inline constants.js]: Although these changes are fine, I don't see the need for them. Can you please explain your rationale? Since the path is basically a constant for a particular OS, I don't see any reason to introduce the three new function calls. Thanks! :slightly_smiling_face:

File: file-module.js [hunk 2]
```diff
@@ -11,12 +11,12 @@ exports.writeLocal = function (solvetime, scramble) {
 exports.checkLocalFile = function () {
   var fileExists = require('file-exists');
   var touch = require('touch');
-  var xdg = require('xdg-basedir');
   var filepath = require('./constants').LOCAL_FILE_PATH;
 
-  if (!fileExists(filepath)) {
+  if(!fileExists.sync(filepath)) {
```
Comment (icyflame) [inline file-module.js]: Drop the `file-exists` dependency and use `fs.existsSync` instead.

File: constants.js (hunk 1 above)
Comment (icyflame) [reply constants.js]: Your `LOCAL_SAVE_DIR` idea is required! Thanks for that, but I would just define it as a constant instead of using `path.join`.

File: file-module.js [hunk 3]
```diff
@@ -49,7 +49,7 @@ exports.writeToPushed = function (glob) {
   var xdg = require('xdg-basedir');
   var filepath = require('./constants').PUSHED_FILE_PATH;
 
-  if (!fileExists(filepath)) {
+  if(!fileExists(filepath)) {
```
Comment (icyflame) [inline file-module.js]: Use fs.existsSync here. Drop file-exists.

File: file-module.js [hunk 4]
```diff
@@ -49,7 +49,7 @@ exports.writeToPushed = function (glob) {
...
     var mkdirp = require('mkdirp');
     mkdirp(xdg.data + '/cube');
```
Comment (icyflame) [inline file-module.js]: Use `mkdirp.sync` here.

File: package.json [hunk 5]
```diff
@@ -27,23 +27,23 @@
...
     "lodash.max": "^4.0.1",
     "lodash.min": "^4.0.1",
     "math-avg": "^1.0.0",
-    "meow": "^3.1.0",
+    "meow": "^3.7.0",
     "mkdirp": "^0.5.1",
-    "pretty-ms": "^1.2.0",
-    "read": "^1.0.6",
+    "pretty-ms": "^3.0.1",
+    "read": "^1.0.7",
```
Comment (icyflame) [inline package.json]: Whoa whoa. This is too much of a change! Bumping major versions is a gamble, and I don't want to do it without thorough testing. So, let's keep this out of the scope of this particular PR. As I mentioned in the other issue's comment, I will freeze versions after merging this PR, test the whole module and if everything works, make a release.

Deprecated warnings suck, but not as much as a module that stops working!

**Review by icyflame — CHANGES_REQUESTED** [review]

**Comment by icyflame** [comment]
Hey, thanks for all your changes. I want to refocus this PR on just creating a new constant in the `constants.js` file, using `fs.existsSync` and `mkdirp.sync` everywhere and removing the `file-exists` dependency. 

The unit test you added is fine and required. Once I merge the template, I will add a few more tests.

File: constants.js (hunk 1 above)
Comment (Jan-Ka) [reply constants.js]: Hi,

This is a best practice in my opinion since it ensures that the path is not malformed or at least normalized. Using `path` should handle all use cases but on the other hand it boils down to preference.

I will honor your opinion on this and change it accordingly.

Comment (icyflame) [reply constants.js]: Hmm, I think `xdg-basedir` is dependable. :slightly_smiling_face: I know what they say about micro-optimizations, but it's still a few function calls I would avoid.

(If things go bad and a bug comes up in the future, because of this, then I will be sure to own up to my error in judgment :smile_cat:  )

**Comment by Jan-Ka** [comment]
@icyflame I just pushed the changes we have discussed. I hope you find everything in order now.

**Comment by icyflame** [comment]
Indeed, everything is in order now. I have merged it into master. I am going to let it be there till maybe tomorrow before freezing everything. Doing a thorough test and then publishing a new version to NPM! Thanks a lot for the time you spent working on this :smile:

**Comment by Jan-Ka** [comment]
Glad I was able to help, I enjoyed it very much and can hopefully provide more help in the future.
